/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.2.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

pluginManagement {
    plugins {
        kotlin("jvm") version "2.1.20"
        kotlin("plugin.serialization") version "2.1.20"
    }
}

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "open-file"
include(
    ":shared",
    ":shared:core",
    ":shared:snapshot",
    ":shared:sql",
    ":shared:mongo",
    ":shared:template",
    ":apps:snapshot:sql",
    ":apps:snapshot:mongo",
    ":apps:template:sql",
    ":apps:template:mongo"
)
include("apps:snapshot:api")
include("apps:template:cli")
include("apps:template:api")